.pages:
  image: python:3.8
  script:
    - pip install poetry
    - poetry install
    - cd docs
    - poetry run pagekey-docgen .
    - rm -rf public
    - cd ..
    - mv docs/build/html public
  artifacts:
    paths:
      - public
pages-dev:
  extends: .pages
  except: [main]
pages:
  extends: .pages
  only: [main]


semantic-release:
  image: node:18.19
  script:
    - npx semantic-release
